#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
#!/bin/sh
red='\033[0;31m'
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo ":hammer::x: ${red} Aborting commit. Your commit message is invalid. Please use yarn commit for better commits...:hammer::x:" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo ":hammer::x:${red} Aborting commit. Your commit message is too long.:hammer::x:" >&2
    exit 1
fi